config/routes.rb
Iftogram::Application.routes.draw do
  get "oauth/auth"
  get "oauth/connect"
  get "oauth/logout"

  #match 'profile/:id' => 'profile#view'
  match 'profile/:id' => 'profile#view', :as => :profile
  get "search/index"
  get "search/result", :controller => :search, :action => :index
  
  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'search#index'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/oauth_controller.rb
require 'json'
require 'instagram'

class OauthController < ApplicationController
  
  def auth
    response = Instagram.get_access_token(params[:code], 
        redirect_uri: oauth_auth_url(return_to_url: params[:return_to_url]))
    session[:access_token] = response.access_token
    client = Instagram.client(:access_token => session[:access_token])
    session[:user] = client.user

    if params[:return_to_url]
      redirect_to params[:return_to_url]
    else
      redirect_to :controller => 'search', :action => 'index'
    end
  end

  def connect
    redirect_to Instagram.authorize_url(:redirect_uri => 
          oauth_auth_url(return_to_url: params[:return_to_url]))
  end

  def logout
    session.clear
    redirect_to search_index_url
  end
end

app/controllers/profile_controller.rb
require 'instagram'
class ProfileController < ApplicationController
  def view
    @result = {}
    begin 
      @result[:media] = Instagram.user_recent_media(params[:id], access_token: session[:access_token])
      @result[:success] = true
    rescue Exception => e
      @result[:success] = false
    end
  end
end

app/controllers/search_controller.rb
require 'instagram'
class SearchController < ApplicationController

  CLIENT_ID = '5941c4645df04708ae67e1ad4b3d6684'
  INSTAGRAM_API_URL = 'https://api.instagram.com/v1/users/search'

  def index
    if params[:q].blank?
      @people = []
    else
      @query = params[:q]
      @people = Instagram.user_search(@query)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/oauth_helper.rb
module OauthHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Iftogram - Instagram from the outside</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
		<div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">Iftogram</a>
          <% if session[:user] %>
<!--            <img src="<%= session[:user].profile_picture %>"/> -->
            <p class="navbar-text pull-right">
              Logged in as <%= session[:user].username %>
              | <%= link_to 'Sign out', oauth_logout_path %> 
            </p>
          <% else %>
            <%= link_to 'Log in with your Instagram account', oauth_connect_path, class: 'navbar-text pull-right' %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="container">
  		<%= yield %>
	  </div>



</body>
</html>

app/views/search/index.html.erb
<form class="well form-search" action="<%= search_result_path %>">
  <div class="input-append">
    <input type="text" class="input-large search-query" name="q" value="<%= @query %>">
    <button class="btn btn-primary" type="submit"><i class="icon-search icon-white"></i> Find users!</button>
  </div>
</form>


<div class="search-results">
  <% @people.each do |person| -%>
    <a href="<%= profile_path(person["id"]) %>">
      <div class="row-fluid item">
        <div class="span3">
          <img src="<%= person["profile_picture"] %>">
        </div>
        <div class="span9">
          <h2><%= person["username"] %></h2>
          <h3><%= person["full_name"] %></h3>
          <p><%= person["bio"] %></p>
        </div>
      </div>
    </a>
    <hr></hr>
  <% end -%>
  test!
</div>

app/views/search/result.html.erb
<h1>Search#result</h1>
<p>Find me in app/views/search/result.html.erb</p>